name: C Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: C benchmarks using GCC 15.2.0

services:
  c-container:
    image: gcc:15.2.0
    command: sleep infinity

flow:
  - name: C-Binary-Trees
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp /tmp/repo/benchmarks/c/binary-trees/main.c -o /tmp/main
      - type: console
        command: /tmp/main 21

  - name: C-Fannkuch-Redux
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp /tmp/repo/benchmarks/c/fannkuch-redux/main.c -o /tmp/main
      - type: console
        command: /tmp/main 12

  - name: Go-K-Nucleotide
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp /tmp/repo/benchmarks/c/k-nucleotide/main.c -o /tmp/main
      - type: console
        command: sh -c "/tmp/main < /tmp/repo/inputs/fasta-2500000.txt"

  - name: C-N-Body
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native /tmp/repo/benchmarks/c/n-body/main.c -o /tmp/main
      - type: console
        command: /tmp/main 50000000

  - name: C-Regex-Redux
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp /tmp/repo/benchmarks/c/regex-redux/main.c -o /tmp/main -lpcre2-8
      - type: console
        command: sh -c "/tmp/main < /tmp/repo/inputs/fasta-2500000.txt"

  - name: C-Spectral-Norm
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp /tmp/repo/benchmarks/c/spectral-norm/main.c -o /tmp/main -lm
      - type: console
        command: /tmp/main 5500
