name: C Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: C benchmarks using GCC 15.2.0

services:
  c-container:
    image: gcc:15.2.0
    command: sleep infinity

flow:
  - name: C-Fasta
    container: c-container
    commands:
      - type: console
        command: gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native /tmp/repo/benchmarks/c/fasta/main.c -o /tmp/main
      - type: console
        command: /tmp/main 25000000
