name: Go Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: Go benchmarks using Golang 1.25 Alpine

services:
  go-container:
    image: golang:1.25-alpine
    command: sleep infinity

flow:
  - name: Go-Binary-Trees
    container: go-container
    commands:
      - type: console
        command: go run /tmp/repo/benchmarks/go/binary-trees/main.go 21

  - name: Go-Fannkuch-Redux
    container: go-container
    commands:
      - type: console
        command: go run /tmp/repo/benchmarks/go/fannkuch-redux/main.go 12

  - name: Go-K-Nucleotide
    container: go-container
    commands:
      - type: console
        command: sh -c "go run /tmp/repo/benchmarks/go/k-nucleotide/main.go < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Go-N-Body
    container: go-container
    commands:
      - type: console
        command: go run /tmp/repo/benchmarks/go/n-body/main.go 50000000

  - name: Go-Regex-Redux
    container: go-container
    commands:
      - type: console
        command: sh -c "go run /tmp/repo/benchmarks/go/regex-redux/main.go < /tmp/repo/inputs/fasta-2500000.txt"

  - name: Go-Spectral-Norm
    container: go-container
    commands:
      - type: console
        command: go run /tmp/repo/benchmarks/go/spectral-norm/main.go 5500