name: Fibonacci Benchmark in Python
author: André Brandão <https://github.com/brandao07>
description: Fibonacci Benchmark in Python

services:
  python-container:
    image: python:3.14.0-alpine3.22
    command: sleep infinity

flow:
  - name: Python-Fibonacci
    container: python-container
    commands:
      - type: console
        command: python3 /tmp/repo/benchmarks/python/fibonacci/main.py