name: NodeJS Benchmark (Default)
author: André Brandão <https://github.com/brandao07>
description: NodeJS benchmarks using Node 25 Alpine

services:
  node-container:
    image: node:25-alpine3.21
    command: sleep infinity

flow:
  - name: NodeJS-Binary-Trees
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/binary-trees/main.js 21

  - name: NodeJS-Fannkuch-Redux
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/fannkuch-redux/main.js 12

  - name: NodeJS-K-Nucleotide
    container: node-container
    commands:
      - type: console
        command: sh -c "node /tmp/repo/benchmarks/nodejs/k-nucleotide/main.js < /tmp/repo/inputs/fasta-2500000.txt"

  - name: NodeJS-N-Body
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/n-body/main.js 50000000

  - name: NodeJS-Regex-Redux
    container: node-container
    commands:
      - type: console
        command: sh -c "node /tmp/repo/benchmarks/nodejs/regex-redux/main.js < /tmp/repo/inputs/fasta-2500000.txt"

  - name: NodeJS-Spectral-Norm
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/spectral-norm/main.js 5500
