name: NodeJS Benchmark (Fasta)
author: André Brandão <https://github.com/brandao07>
description: NodeJS benchmarks using Node 25 Alpine

services:
  node-container:
    image: node:25-alpine3.21
    command: sleep infinity

flow:
  - name: NodeJS-Fasta
    container: node-container
    commands:
      - type: console
        command: node /tmp/repo/benchmarks/nodejs/fasta/main.js 25000000
